### ISSUE TITLE
Running on a Cordova App on Android...

### ISSUE THREAD

**Issue by MuTLY** [onury/geolocator#10]
...I'm getting this:

``GET https://www.google.com/jsapi?callback=geolocator.__glcb net::ERR_CACHE_MISS ``

Any ideas why? It works ok on the desktop browser.

**Comment by onury** [comment]
Hi, this seems to be unrelated with geolocator but rather a missing `INTERNET` permission. 

As [this](http://stackoverflow.com/a/22311550/112731) post suggests, try to include the line below:

```xml
<uses-permission android:name="android.permission.INTERNET" />
```
Also setting these permissions below might also help:
```xml
<uses-permission android-name="android.permission.NETWORK_ACCESS" />
<uses-permission android-name="android.permission.ACCESS_NETWORK_STATE" />
```
Another [related](http://stackoverflow.com/a/26653204/112731) post here.

Please let me know if this works.

**Comment by MuTLY** [comment]
Thank you, it worked.

Apparently, it was the lack of INTERNET and NETWORK_ACCESS permissions.

Funny thing is, ACCESS_NETWORK_STATE was already defined on *cordova\project\platforms\android\AndroidManifest.xml* but there is no ``<uses-permission .. />`` on *cordova\project\config.xml*

Anyways, I put those lines on both files just to make sure.

**Comment by onury** [comment]
You're welcome. Always good to hear it works!
