### ISSUE TITLE
Add "Where Y'at" GeoIP provider

### ISSUE THREAD

**Issue by aensley** [onury/geolocator#15]
This seems like a great GeoIP provider in line with existing options.

 1. http://www.wherey.at/
 1. https://ip.wherey.at/
 1. https://github.com/WhereYat/whereyat-js

**Comment by onury** [comment]
Geolocator v2 (released) now uses Wikimedia for Geo-IP, by default.
No longer supporting multiple Geo-IP sources. 

If you want to use geoplugin or another provider, pls choose one from [ready-to-use configurations](https://github.com/onury/geolocator/tree/master/src/geo-ip-sources) and/or use [`geolocator.setGeoIPSource()` method](https://onury.github.io/geolocator/?api=geolocator#geolocator.setGeoIPSource).

Thanks.
