### ISSUE TITLE
CommonJS support

### ISSUE THREAD

**Issue by namuol** [onury/geolocator#16]
Since the package is on NPM, it would be nice if `module.exports` were utilized if available -- currently `require('geolocator')` returns `undefined`.

**Comment by am-karl** [comment]
+1 for this

**Comment by lostpebble** [comment]
Yes please. This is default expected behaviour for packages on NPM.

**Comment by onury** [comment]
Thanks. Ok. 
This will be implemented in the next release.

**Comment by tcastelli** [comment]
+1

**Comment by khmelevskii** [comment]
+1

**Comment by onury** [comment]
This is implemented in v2 (released).
Thanks.
