### ISSUE TITLE
net::ERR_INSECURE_RESPONSE upon calling geolocator.locateByIP

### ISSUE THREAD

**Issue by asoesilo** [onury/geolocator#19]
I have been getting the following error message upon calling `geolocator.locateByIP` starting today:

> GET https://www.geoplugin.net/json.gp?jsoncallback=geolocator.__ipscb net::ERR_INSECURE_RESPONSE

**Comment by onury** [comment]
Thanks for reporting. 
It seems GeoPlugin no longer provide a free service if HTTPS is used. 

They say you need an "inexpensive SSL key". And they've changed the base secure URL to https://ssl.geoplugin.net
See [details here](http://www.geoplugin.com/webservices/ssl). 
But it will still work from HTTP pages.

Please use other IP sources (wikimedia) for the time being. Next release will provide more options to configure the geo-source which should resolve issues like this.

**Comment by asoesilo** [comment]
Hi onury,

Thanks for looking into this. I've created a simple repo to overcome this issue for now: https://github.com/asoesilo/geolocator.

**Comment by onury** [comment]
Geolocator v2 (released) now uses Wikimedia for Geo-IP, by default.
No longer supporting multiple Geo-IP sources. 

If you want to use geoplugin or another provider, pls choose one from [ready-to-use configurations](https://github.com/onury/geolocator/tree/master/src/geo-ip-sources) and/or use [`geolocator.setGeoIPSource()` method](https://onury.github.io/geolocator/?api=geolocator#geolocator.setGeoIPSource).

Thanks.
