### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by grammka** [onury/geolocator#20]
Hey. If there is any way to control response language of json?

**Comment by onury** [comment]
Hi. I'm not sure what you mean by "response language of JSON".
Do you mean format of the response? or localization language?

**Comment by grammka** [comment]
localization. Coz now from different IPs I get different lang.. If I want always receive response in english can I configure this?

**Comment by onury** [comment]
Can you paste a non-english response here? and pls tell me which IP geo-service you're using.

**Comment by grammka** [comment]
My IP: 109.252.20.45
From ur example http://rawgit.com/onury/geolocator/master/example/index.html (I tried ALL 3 geo services) I'm getting:
```javascript
{
    Latitude: 55.752201
    Longitude: 37.615601
    City: Москва
    Country: Россия
    Country Code: RU
    Region: город Москва
}
```
But from my server in USA instead 'Москва' I get 'Moskva'.. and there is the mistake coz 'Москва' in english is Moscow...

**Comment by onury** [comment]
Ok. IP geo-sources generally return limited data — mostly lat and lon. Missing details (such as city, country, etc) are fetched by reverse address lookup via Google APIs. And the geocoding API does not seem to have a configuration for localization.

**Comment by grammka** [comment]
Thank you for answer.

**Comment by anotheri** [comment]
@grammka @onury 

actually as far as i see there is a way to define language: https://developers.google.com/loader/#googleload

so this line should be updated with `language` option, and also you can include google maps by yourself with proper language parameter, for example:

```
<script src="https://maps.googleapis.com/maps/api/js?key=APIKEY&language=en" ></script>
```

Should be executed properly by this code: https://github.com/onury/geolocator/blob/master/src/geolocator.js#L90

**Comment by onury** [comment]
Now with version 2, you can set language via `geolocator.config(options)` method. 
See [documentation](http://onury.github.io/geolocator/?api=geolocator#geolocator.config) for details.
