### ISSUE TITLE
Why does geolocator always "loadGoogleMaps"?

### ISSUE THREAD

**Issue by rubenstolk** [onury/geolocator#23]
I don't think this is always needed for developers who simply want to fetch a location?

**Comment by onury** [comment]
Thanks. This is being addressed in version 2 (to be released soon).

**Comment by martinec** [comment]
Hi. Some update on this issue. Thank you

**Comment by cynngah** [comment]
Hi just wondering when v2 will be released with this feature? Thanks.

**Comment by onury** [comment]
This is resolved in v2 (released).
Thanks.
