### ISSUE TITLE
HTML5-Geolocation not accurate/dated

### ISSUE THREAD

**Issue by cseelus** [onury/geolocator#28]
We just evaluated your (nicely implemented) script, together with some alternatives in a field tests (iPhone 5, 6, 6s all running iOS 9.3.1) within an area of about 5 sq miles.

We discovered it has a known issue (that many other comparable solutions also have),
 which is described in-depth and solved by a Google Cloud employee called Greg Wilson (no affiliation with him) in a [Github repo](https://github.com/gwilson/getAccurateCurrentPosition#background) of him.

**Comment by onury** [comment]
Excellent feedback @cseelus. I'm looking into this. Thanks.

**Comment by onury** [comment]
This is implemented in v2 (released).
Thanks.

**Comment by cseelus** [comment]
We undertook another field test just now and unfortunately the problem persists.

We used some iPhones (5, 6, 6s) with iOS9 and iOS10 Beta 1, while moving from location to location via car. The locations we tested where around 500m-5km apart. In some cases the Phones apparently used a cached location, although `enableHighAccuracy` was set to `true`.

The following config/setting was used:

```javascript
geolocator.config({
  language: 'en',
  google: {
    version: '3',
    key: 'our_google_api_key'
  }
});

var geolocator_options = {
  enableHighAccuracy: true,
  maximumAge: 0,
  timeout: 15000,
  desiredAccuracy: 5,
  addressLookup: true,
  map: 'map-canvas'
};
```

**Comment by onury** [comment]
Great that you field test this. Thanks @cseelus.
Have you tried Greg Wilson's implementation at the same time? Does it give you different results?

**Comment by cseelus** [comment]
No problem, thanks for your  great work.

Yes, we use Greg Wilsons implementation currently (and for comparison) and the results are as expected, e.g. the accuracy is on par with Google Maps (via their webapp).

**Comment by onury** [comment]
I think it's more accurate now. v2.1.0 is [released](https://github.com/onury/geolocator/blob/master/CHANGELOG.md).

Pls let me know if you test the new.

**Comment by cseelus** [comment]
Hello @onury, sry for the delay, lots of work lately.

Accuracy was never a problem for us using HTML5 geolocation with your utility. The problem is, that in ~10% of testing on the go, we get back a cached location instead of the current real one. 
So for example we drive to location A, use it and get back location A. We drive to location B and get back location B. We drive to location C and get back location B, so we have to run it again (sometimes a few times) to get back the actual location C.

One can immediately tell when a cached location was used, as the location is returned immediately, instead of it taking a few seconds.

I've created a very basic [Plunker example of how we use your utility](http://plnkr.co/edit/LEYsRzD3rxSCMe9TAesR?p=preview). For comparison I also extracted a very basic example of the [HTML5 geolocation script we currently use](http://plnkr.co/edit/ctJMEJM1JkYAw8PNsnJF?p=preview) in our webapp. It is admittedly very primitive and rudimentary in comparison with geolocator, but it works 100% of the time, without returning cached results.

**Comment by onury** [comment]
Hi @cseelus. No worries and thanks a lot for taking the time.
I'll have a closer look into this as soon as I find the time.
We'll nail it this time 😊

**Comment by cseelus** [comment]
Hi @onury. For a new app we're using your well written Geolocator now. I set up [a simple test page](http://imeos.com/onury-geolocator-test/) and drove around by car, testing the accuracy. Works like a charm. Only maybe 1 in 10 or 20 times maximum the iPhone 8 (all other iOS LocationServices switched off) I tested, came back immediately with a location, using a cached one which was a few hundred meters off (returning the last position Geolocator was used).

I think the problem appears only when the time between two invocations of `locate` is very short (~1-2 minutes), so not a dealbreaker. 

Maybe an option like `minimumWait`, which would invoke `watchPosition` in the background for the specified amount of time and `locate` afterwards could mitigate that little problem by forcing the device to retrieve the current position.

**Comment by cseelus** [comment]
Hi @onury. For a new app we're using your well written Geolocator now. I set up [a simple test page](http://imeos.com/onury-geolocator-test/) and drove around by car, testing the accuracy. Works like a charm. Only maybe 1 in 10 or 20 times maximum the iPhone 8 (all other iOS LocationServices switched off) I tested, came back immediately with a location, using a cached one which was a few hundred meters off (returning the last position Geolocator was used).

I think the problem appears only when the time between two invocations of `.locate` is very short (~1-2 minutes), so not a dealbreaker. 

Maybe an option like `minimumWait`, which would invoke `.watch` in the background for the specified amount of time and `.locate` afterwards could mitigate that little problem  (which might be an implementation problem from the device manufacturer, e.g. Apple) by forcing the device to retrieve the current position.

**Comment by onury** [comment]
Hi @cseelus. It's friends like you, help make it near perfect. Thanks again for field-testing. cheers :beer:

This is interesting. When `enableHighAccuracy` option is enabled, Geolocator will already use the accurate watcher by default and ignore the first cycle of speedy result. I assume this option was already enabled in your tests, right?

### Thinking loud:

`minimumWait` sounds ok but I think same issue could still occur. (weak 3/4G connections, GPS delays, etc).  How about `minimumCycles`?
- `minimumCycles` set to `3` (let's say)
- Geolocator will store the first result (cycle 1) as a reference.
- If on the next cycle, it gets a different result; it will immediately return without waiting for the 3rd.
- Otherwise, it will at least wait for another cycle (3 in total) and return the last.
- If `minimumCycles` is set to `1`, it has no affect.

Sounds logical?

**Comment by cseelus** [comment]
No need to thank me. Its people like you, who write great open-source software, that keep the web going. 🍻

Yes, `enableHighAccuracy` as well as `maximumAge` are enabled [on the test-site](https://imeos.com/onury-geolocator-test). When Geolocator already uses `watchPosition`, even for one-time lookups via `locate` I guess the problem really is on the Device/OS side.

Your idea with `minimumCycles` sounds great, certainly more elegant than a `minimumWait` option.

**Comment by onury** [comment]
ok @cseelus I'll give it some more thought.
I'm a bit busy now, I'll implement this as soon as I can.

**Comment by cseelus** [comment]
Thx very much ✌🏼

**Comment by cseelus** [comment]
I have to say now, that feature isn't really necessary in practice. Zero user-complaints in production :-)

As I said above, only when the time between two invocations of `.locate` is very brief, a not up-to-date location will be used. This will only matter when a user moves quite fast between two locations, which is only relevant for some very specific use-cases, so it might not be worth your while.

Thanks again for your work. Cheers!

**Comment by onury** [comment]
Good to know that.. And glad to hear you have happy users!
I'll take it easy then :)) but still keep this in roadmap, though..

Thanks for kindly letting me know. Cheers!

**Comment by cseelus** [comment]
Let me know if I/we can help testing if you should implement that feature.

**Comment by onury** [comment]
Thanks Chris. Sure I'll notify you.
