### ISSUE TITLE
ip look-up is very inaccurate

### ISSUE THREAD

**Issue by jasan-s** [onury/geolocator#35]
tried www.iplocation.net for ip look lat long, and it is much more accurate. why is that

**Comment by onury** [comment]
If you're getting inaccurate location from an IP lookup, that's bec. of the IP-location database that service is using. By default, Geolocator uses **Wikimedia**'s Geo-IP endpoint for IP-lookups; which uses [MaxMind](https://www.maxmind.com/en/home)'s database.

We cannot measure which database is more accurate than the other. I mean, for my location the IP range might be more accurate than your location in database X and vice-versa for database Y. These databases are said-to-be updated periodically. 

If you're not satisfied with the results of an IP-lookup, you can [configure geolocator](http://onury.github.io/geolocator/?api=geolocator#geolocator.setGeoIPSource) to use a different service. You can also check out these [ready-to-use configurations](https://github.com/onury/geolocator/tree/master/src/geo-ip-sources).
