### ISSUE TITLE
https://bits.wikimedia.org/geoiplookup Not Found

### ISSUE THREAD

**Issue by mashleyttu** [onury/geolocator#36]
Hi, 

It seems as though starting at some point last week the locate by IP Address is failing.

 {name: "GeoError", code: "UNKNOWN_ERROR", message: "Could not load source at https://bits.wikimedia.org/geoiplookup↵[object Event]"}
code
:
"UNKNOWN_ERROR"
message
:
"Could not load source at https://bits.wikimedia.org/geoiplookup↵[object Event]"
name
:
"GeoError"
stack
:
(...)

Thanks for any assistance you can provide.
Matt

**Comment by onury** [comment]
Seems like Wikimedia endpoint is down.
I'll wait a few days to check if it'll be up again; and update geolocator.js if still needed.

Until then you can [configure geolocator](http://onury.github.io/geolocator/?api=geolocator#geolocator.setGeoIPSource) to use a different service.
Check out these [ready-to-use configurations](https://github.com/onury/geolocator/tree/master/src/geo-ip-sources). *freegeoip* would be good choice.

**Comment by onury** [comment]
Here is status page for wikimedia services. 
https://status.wikimedia.org

**Comment by ddimaria** [comment]
The service is still down, and is now throwing a 404.  It's easy to use freegeoip, just the copy code and add to you JS before you invoke locate(): https://github.com/onury/geolocator/blob/master/src/geo-ip-sources/freegeoip.js

**Comment by LuisMejiaF** [comment]
The GeoIP service is not longer listed in the [status page](https://status.wikimedia.org), so I guess it is better to remove it as the default provider.

Thanks for leaving this library open for using other providers, now I'm using freegeoip.

**Comment by onury** [comment]
Thanks. 
Geolocator v2.1.0 is released. Pls see the [change-log](https://github.com/onury/geolocator/blob/master/CHANGELOG.md).
