### ISSUE TITLE
The 'raw' option never gets to be used

### ISSUE THREAD

**Issue by edudiego** [onury/geolocator#41]
Passing **raw = true** in the options for **Gelolocate.locate** does not have any effect  when  we have **options.addressLookup** set to true.

When **addressLookup = true**, the **loc.coords** object is passed to **geolocator.reverseGeocode** and at this point options.raw is lost.

**Comment by onury** [comment]
The [`.locate()` method](http://onury.github.io/geolocator/?api=geolocator#geolocator.locate) has no `raw` option. Besides, it's a method that combines multiple requests from different resources. Returning raw response is not logical.

The `raw` option is for Google APIs mostly. It's supported by simple methods that do only one thing; such as `addressLookup()`, `getTimeZone()`, etc..

**Comment by edudiego** [comment]
Thanks for the quick response Onury! 

Do you suggest some way to get the array of possible addresses using the Geolocator API? Otherwise when it gets to addressLookup I don't have the raw option anymore.

What I am doing now is changing the response object to contain both the results array and the formated address:

response = options.raw ? response : _utils2.default.extend({}, response, geoHelper.formatGeocodeResults(response.results));

**Comment by onury** [comment]
I assume you want to get the original response of a Google reverse-geocode (address lookup) request. This is how you do it:

```js
geolocator.config({
    language: "en",
    google: {
        version: "3",
        key: "YOUR-GOOGLE-API-KEY"
    }
});

var options = {
    latitude: 37.4224764,
    longitude: -122.0842499,
    raw: true
};

geolocator.reverseGeocode(options, function (err, response) {
    console.log(err || response);
});
```
This will return: `{ results: [...], status: "OK" }`
`response.results` is the array of addresses.
