### ISSUE TITLE
Uncaught TypeError: Cannot read property '_' of undefined(…)

### ISSUE THREAD

**Issue by EmpireJones** [onury/geolocator#42]
Any ideas what I'm doing wrong? Or if this is a geolocator library bug? I only get this when blocking location usage in the browser (which kicks off the fallback functionality).

VM1457:2989 Uncaught TypeError: Cannot read property '_' of undefined(…)
(anonymous function) @ VM1457:2989
notateGlobalObj @ VM1457:2988
jsonp @ VM1457:3382
locateByIP @ VM1457:986
fallbackToIP @ VM1457:704
onPositionError @ VM1457:716

"geolocator":"2.1.0"

	import geolocator from 'geolocator'

	geolocator.config({
		language: "en"
	});

	var options = {
		enableHighAccuracy: false,
		timeout: 5000,
		maximumAge: 1800000,
		fallbackToIP: true
	};
	geolocator.locate(options, function (err, location) {
		...
	}

**Comment by onury** [comment]
It seems `geolocator` object is not globally available in the browser.
Are you sure you've included it in your page?

**Comment by onury** [comment]
Sorry you say you get this when it falls back to IP.
I just tested your scenario in Chrome and Safari. Had no problems.
Which browser are you using?

**Comment by EmpireJones** [comment]
I'm using webpack/babel/node for this. Does this require that I explicitly source the script in my html? It seems to work when I do that, although that's very much undesirable.

When I just use the node package, it looks like notateGlobalObj is unable to find the geolocator object, as you mentioned. And yes, this only happens with the fallback.

I don't think this is a browser-specific issue. The example site works fine. I'm using Chrome and Firefox in Ubuntu.

**Comment by onury** [comment]
The problem that; when you import/require geolocator, it seems it does not get assigned to the `window` object.

The fallback invokes the `.locationByIP()` method which internally executes a JSONP request. The callback of the JSONP is a method of private `geolocator._` object. So browser executes `geolocator._.cb({...})` but `geolocator` is `undefined`.

It should be global. `<script />` tag is one way to do that. But if you don't want that, I can imagine 2 workarounds:
 1. Try assigning it yourself after you import/require geolocator. 
   ```js
   import geolocator from 'geolocator';
   window.geolocator = geolocator;
   ```
  2. Try bundling geolocator together with your code, in webpack config.

Let me know if this resolves the problem.

_Note: If first one works, I'll update the source accordingly so you won't have to do it with next minor release._

**Comment by EmpireJones** [comment]
I didn't try workaround 2, but it looks like workaround 1 does the job. Thanks for the help and for creating this library! :+1:

**Comment by onury** [comment]
This is added in [v2.1.1](https://github.com/onury/geolocator/blob/master/CHANGELOG.md#v211-2017-03-11).
