### ISSUE TITLE
Better Fallback

### ISSUE THREAD

**Issue by celiovasconcelos** [onury/geolocator#45]
The `freegeoip` has not a good accuracy.

Is it possible to fallback to the google api once the user deny getting coordinates by html5?

```
google.load("maps", "2.x", {callback: initialize});

function initialize() {
  if (google.loader.ClientLocation) {
      var lat = google.loader.ClientLocation.latitude;
      var long = google.loader.ClientLocation.longitude;
      console.log("lat: " + lat + "\nlong: " + long);
   }
   else { alert ("not available"); }
 }
```

**Comment by onury** [comment]
Sure. You can fallback to anything like this:
```
...
options.fallbackToIP = false;
geolocator.locate(options, function (err, location) {
    if (err) {
        someOtherMethod();
    } else {
        console.log(location);
    }
});
```

But `google.loader.ClientLocation` is deprecated years ago. I think it's obsolete by now. It returns `null`.

Check out [this comment](https://github.com/onury/geolocator/issues/35#issuecomment-244420807) on how to use a different provider for IP-based geolocation.
