### ISSUE TITLE
Locate on examples throws DomException

### ISSUE THREAD

**Issue by edericogrocha** [onury/geolocator#46]
On the [examples](https://onury.github.io/geolocator/?content=examples) page, the first Locate throws an error: 
VM51:47 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned.(…)

I am using Chrome Version 54.0.2840.100 (64-bit).

**Comment by onury** [comment]
VMxyz is logs are generated by dev-tools for dynamically injected scripts. That looks like an chrome-extension error.

The examples page should log an error for "examples.js" or "geolocator.js" if the error is related to  Geolocator. Examples work as expected on Chrome 54, 55..

You could disable your extensions and re-try.

**Comment by edericogrocha** [comment]
You're right. I don't have this issue using Firefox. Something is messing with the chrome extensions. Thanks
