### ISSUE TITLE
request geolocation only IP ? 

### ISSUE THREAD

**Issue by cedvdb** [onury/geolocator#47]
when the HTML 5 geolocation is used it takes a while to get the info I need. I'd like to only do the geolocation via ip as it is way faster. Is there a built in way to do so ?  

I tried enableHighAccuracy set to false but it didn't do the trick.

**Comment by onury** [comment]
Sure. You can use `.locateByIP()` method.
```js
geolocator.locateByIP(options, function (err, location) {
  console.log(err || location);
});
```
Pls refer to the [detailed documentation here](http://onury.github.io/geolocator/?api=geolocator#geolocator.locateByIP).

But note that you won't get accurate location via Geo-IP. It will resolve to a city at most.
For coordinates-accuracy you should use HTML5 features via `.locate()` method, which will use the GPS device for location.
