### ISSUE TITLE
Invalid location error

### ISSUE THREAD

**Issue by drekay** [onury/geolocator#50]
I am getting - Failed to load resource: the server responded with a status of 400 (Bad Request)

https://maps.googleapis.com/maps/api/timezone/json?location=50.1234,-1.2132×tamp=1493128056&language=en&key=here

where × is %C3%97

For the purpose of this question I changed **lat** and removed the **key**.

The Example included works fine on the same server.

Please advise what is wrong.

**Comment by onury** [comment]
Your example doesn't even work in the browser. Even when `x` replaced with `%C3%97` and `key` with a valid key; you get `INVALID_REQUEST`.

There is no `tamp` parameter in the Timezone query-string. It should be `timestamp`. If you're using geolocator properly, this field is auto-set; if you omit it in the options passed to `.getTimeZone()` method..

Pls read [`geolocator.getTimeZone()`](https://onury.github.io/geolocator/?api=geolocator#geolocator.getTimeZone) documentation and ensure you're setting options correctly.

**Comment by drekay** [comment]
Thanks for the quick response.

However, I did not manually specify the coordinates ending with x ( %C3%97) or the parameter 'tamp' . I have been searching online what could be causing that with respect to Google's GeoLocation API or Timezone API. The closest thing I found was that the coordinates needs to have precision no more than 6 yet I am getting precision of 4 digits.

I am only interested in the Timezone Offset for UTC so the code is very basic as shown below:

  <script type="text/javascript">
        geolocator.config({
        language: "en",
        google: {
            version: "3",
            key: "MY-KEY"
        }
    });
   timezone = 0;
  window.onload = function () {
        var options = {
            enableHighAccuracy: true,
            timeout: 1000,
            maximumWait: 1000,     // max wait time for desired accuracy
            maximumAge: 0,          // disable cache
            desiredAccuracy: 30,    // meters
            fallbackToIP: true,     // fallback to IP if Geolocation fails or rejected
            addressLookup: true,   // requires Google API key if true
            https: true,
            timezone: true
        };
        geolocator.locate(options, function (err, location) {
            if (err) return console.log(err);
            console.log(location);
         
          if (location.timezone.dstOffset == 0) 
             timezone = location.timezone.rawOffset;
          else
            timezone =  location.timezone.dstOffset;
          console.log(timezone);


        });
    };
</script>

Doing anything wrong here?

**Comment by onury** [comment]
Your url seems to get HTML encoded before passed to Geolocator. 

Example URL:
`https://maps.googleapis.com/maps/api/timezone/json?location=41.900000,12.400000&timestamp=1493128056`

- breakdown the parameters:
`location` = `41.900000,12.400000`
`&` -> qs separator
`timestamp` = `1493128056`

Somehow your url gets encoded..  
This might happen when you put raw URL within HTML.
See [this example](https://jsfiddle.net/huufwftq/). 

-  `&times` part of `&timestamp=...` is an HTML entity 
which produces unicode character `×`. 

- When this is the case `&` is removed, and now the value of the `location` parameter changes.
`location` = `41.900232342,12.48234234234×tamp=1493128056` 
Notice `×tamp=..`

- Then this gets URL encoded. 
`location` = `41.900000%2C12.400000%C3%97tamp%3D1493128056.`
Notice `%C3%97` part which is  `×`.

Now I don't get how URL is encoded this way if you're not putting it in your HTML but using Geolocator instead. Geolocator doesn't do that.

**Comment by drekay** [comment]
For some reason everything works fine if I use geolocator.js and not geolocator.min.js.

I have tried so many arrangements - placing the above script in the <head>, <body>, <footer> sections but can't get it work with geolocator.min.js. So I will stick to geolocator.js for now until I/anyone figure/s this out.

Thanks for your help and useful library.
