### ISSUE TITLE
Demo pages not using HTTPS

### ISSUE THREAD

**Issue by Jamesking56** [onury/geolocator#51]
Hello,

As stated in your own README:

> Make sure you're calling Geolocation APIs (such as geolocator.locate() and geolocator.watch()) from a secure origin (i.e. an HTTPS page). In Chrome 50, Geolocation API is removed from unsecured origins. Other browsers are expected to follow.

Since the demo is not using HTTPS, the demo doesn't ask for location in Google Chrome.

Please put the demo pages under HTTPS, its free using Let's Encrypt now!

**Comment by onury** [comment]
Thanks. Using CloudFlare now.
Pls empty you cache if you still get the old site.
