### ISSUE TITLE
FreeGeoIP service is shut down

### ISSUE THREAD

**Issue by RK-Rivero** [onury/geolocator#53]
Hi Guys!

I've been had problems with the displaying of the map and I think is because FreeGeoIP has deprecated the API and now is called "IP Stack"; is on yours plans to fix this bug?

**Comment by onury** [comment]
Thanks for reporting. [This](https://github.com/apilayer/freegeoip#readme) indicates that the service would be shut down on July 1st, 2018 but seems they did it already.

I'm trying to keep up with these kinds of changes but you can always set a different Geo-IP source via `geolocator.setGeoIPSource()` method. See [ready-to-use examples](https://github.com/onury/geolocator/tree/master/src/geo-ip-sources).

Expect a patch release with a fix for this shortly.

**Comment by onury** [comment]
FreeGeoIP was the only free provider (in ready-to-use providers) that had HTTPS support. See [caveats section](Update: See https://github.com/onury/geolocator#caveats) for what this actually means for geolocator.

Added [nekudo](https://github.com/nekudo/shiny_geoip) service instead. This has free HTTPS support but should be used responsibly.

**Comment by RK-Rivero** [comment]
Thanks man!
I do appreciate a lot :D
