### ISSUE TITLE
locateByMobile returns 400/404 error

### ISSUE THREAD

**Issue by doubleedesign** [onury/geolocator#59]
When using locateByMobile with minimal options, I get a 404 error in the console for the GoogleAPIs URL. When using the example page at https://onury.io/geolocator/?content=examples, similar happens except it's a 400 error instead, so it looks like there's something wrong with locatebyMobile since even the example site doesn't work.

**Comment by onury** [comment]
The example site will work if you enter your own Google API key and enable the used APIs for your key. It gets too many hits so the key there is generally over-used.

Geolocator uses the exact endpoint indicated in [Google API docs](https://developers.google.com/maps/documentation/geolocation/intro).

Before you start developing with the Geolocation API, review the [authentication requirements](https://developers.google.com/maps/documentation/geolocation/get-api-key) (you need an API key) and the API [usage and billing](https://developers.google.com/maps/documentation/geolocation/usage-and-billing) information (you need to enable billing on your project).

**Comment by doubleedesign** [comment]
Yeah I did enter my key, which otherwise seems to authenticate fine (the requests are going through and can be seen in the Google API console). Are any of the fields, such as country code, required? I didn't think they were but figured I'd ask anyway in case that's what I have wrong...

![capture](https://user-images.githubusercontent.com/563583/46536217-277d5980-c8f1-11e8-864f-091f233dc886.PNG)

**Comment by doubleedesign** [comment]
Thanks for the links...does this mean I need to somehow provide wifi and cell tower objects? How would one get that information on the fly? (I thought it just looked for nearby ones automatically). 

> BTW, is there any specific reason you're using locateByMobile() instead of locate() ? 

An attempt at better accuracy - HTML5 geolocation is only good if the user allows it and the client was  complaining about how inaccurate the feature appears to be (because it defaults to locating by IP). Currently, I have the IP fallback turned off, but then manually run locate() if locateByMobile() fails, and locateByIP() if locate() fails (I know I could just set locate() to fall back to IP but I'm also showing different explanatory messages at each stage). 

Thank you for your time and suggestions!

**Comment by onury** [comment]
You're welcome.

Ok, that API will not provide a valuable result with no pre-settings. `locateByMobile()` would only be useful if you know the region the user is in, then attempt to get better accuracy from it. 

In other words, you might try `locate()` with fallback to IP first. Then with whatever result you get, you might try to improve the location accuracy by attempting a `locateByMobile()` if you have some extra info about the region.

**Comment by onury** [comment]
> does this mean I need to somehow provide wifi and cell tower objects?

The Google docs says you don't. But in my tests, I never got proper results with this. It seems Google does not have an up-to-date database for every country/region or cell towers, etc.. What it does is, it also falls back to IP-based location then lookup tower info from it's db, if it exists.. But generally it doesn't find anything. (at least for my country).
