### ISSUE TITLE
There are no tags

### ISSUE THREAD

**Issue by jemiam** [onury/geolocator#9]
Hi. I want to use geolocator via rails-assets. But when I tried to create new component at https://rails-assets.org/components/new , i got an error.

```
geolocator has no versions defined. Please create an issue in component's repository.
```
Can you please tag it?

**Comment by onury** [comment]
Hi there. Created release [v1.2.8](https://github.com/onury/geolocator/releases/tag/v1.2.8). This should work for rails-assets.

**Comment by jemiam** [comment]
@onury Thanks!
